[build]
  command = "ROLLUP_NATIVE_DISABLE=1 npm i && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-optional --legacy-peer-deps"
  ROLLUP_NATIVE_DISABLE = "1" 